[dev]
	command = "npm run start:vite"
	publish = "dist"
	targetPort = 5173
	functionsPort = 5174
	port = 8888
	framework = "#custom"

[build]
	command = "npm run build:vite"
	publish = "dist"

[functions]
	directory = "./src/functions"
	node_bundler = "esbuild"

[[redirects]]
	from = "/id"
	to = "/.netlify/functions/id"
	status = 200

[[redirects]]
	from = "/api/*"
	to = "/.netlify/functions/:splat"
	status = 200

[[redirects]]
	from = "/*"
	to = "/index.html"
	status = 200

[template.environment]
	TMDB_API_KEY = "TMDB API Key"
	GIANTBOMB_API_KEY = "Giant Bomb API key"